export const ACCOUNT_FORM_NAME = 'account'
export const LOGIN_FORM_NAME = 'login'
export const SIGNUP_FORM_NAME = 'signup'
export const NEW_WORDBANK_FORM_NAME = 'newWordbank'
export const NEW_WORD_FORM_NAME = 'newWord'
