/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .travis.yml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'local'

// Config for firebase
export const firebase = {
  apiKey: 'AIzaSyDYFteY5wAzyiXixHyeN0gUq9V97luPiHw',
  authDomain: 'vocacoord-dev-jerry.firebaseapp.com',
  databaseURL: 'https://vocacoord-dev-jerry.firebaseio.com',
  projectId: 'vocacoord-dev-jerry',
  storageBucket: 'vocacoord-dev-jerry.appspot.com',
  messagingSenderId: '755182670601'
}

// Config to override default reduxFirebase config in store/createStore
// which is not environment specific.
// For more details, visit http://react-redux-firebase.com/docs/api/enhancer.html
export const reduxFirebase = {
  enableLogging: false // enable/disable Firebase Database Logging
}

export const analyticsTrackingId = ''

export const publicVapidKey =
  'BF6YpO--fDPUtZpEEkY0zh-DRAjEA32bhSFElogsbL_KTECYkcIt0zdCLf7znI5z0HDkLf8bLz1pNZJsOFVU21Q'

export const sentryDsn =
  'https://7bdc42733dcc406c9227ea2a637e9421@sentry.io/1381805'

export default {
  env,
  firebase,
  reduxFirebase,
  sentryDsn,
  publicVapidKey,
  analyticsTrackingId
}
