/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .travis.yml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'local'

export const firebase = {
  apiKey: 'AIzaSyA5Skf8JFsuH_RMC4AA_-xeKjdJKGPfJ0I',
  authDomain: 'vocacoord.firebaseapp.com',
  databaseURL: 'https://vocacoord.firebaseio.com',
  projectId: 'vocacoord',
  storageBucket: 'vocacoord.appspot.com',
  messagingSenderId: '317432010698'
}

export const reduxFirebase = {
  enableLogging: false
}

export const publicVapidKey =
  'BF6YpO--fDPUtZpEEkY0zh-DRAjEA32bhSFElogsbL_KTECYkcIt0zdCLf7znI5z0HDkLf8bLz1pNZJsOFVU21Q'

export const sentryDsn =
  'https://7bdc42733dcc406c9227ea2a637e9421@sentry.io/1381805'

export default {
  env,
  firebase,
  reduxFirebase,
  sentryDsn,
  publicVapidKey
}
