/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .travis.yml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'local'

export const firebase = {
  apiKey: 'AIzaSyDYFteY5wAzyiXixHyeN0gUq9V97luPiHw',
  authDomain: 'vocacoord-dev-jerry.firebaseapp.com',
  databaseURL: 'https://vocacoord-dev-jerry.firebaseio.com',
  projectId: 'vocacoord-dev-jerry',
  storageBucket: 'vocacoord-dev-jerry.appspot.com'
}

export const reduxFirebase = {
  enableLogging: false
}

export const sentryDsn =
  'https://7bdc42733dcc406c9227ea2a637e9421@sentry.io/1381805'

export default {
  env,
  firebase,
  reduxFirebase,
  sentryDsn
}
